"""empty message

Revision ID: a1ad8e29aad1
Revises: a264910dc4a1
Create Date: 2024-10-04 18:40:04.817293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ad8e29aad1'
down_revision = 'a264910dc4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_favorito', sa.Integer(), nullable=True),
    sa.Column('characters_favorito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_favorito'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['user_favorito'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes_favoritos')
    # ### end Alembic commands ###
