"""empty message

Revision ID: b9908222a7d1
Revises: 6ae2f9963f6d
Create Date: 2024-10-05 01:52:59.468331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9908222a7d1'
down_revision = '6ae2f9963f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_favorito', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('personajes_favoritos_personaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personajes', ['personaje_favorito'], ['id'])
        batch_op.drop_column('personaje_id')

    with op.batch_alter_table('planetas_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_favorito', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('planetas_favoritos_planeta_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planetas', ['planeta_favorito'], ['id'])
        batch_op.drop_column('planeta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planetas_favoritos_planeta_id_fkey', 'planetas', ['planeta_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('planeta_favorito')

    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personajes_favoritos_personaje_id_fkey', 'personajes', ['personaje_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('personaje_favorito')

    # ### end Alembic commands ###
